platform :ios, '9.0'

use_frameworks!
source 'https://gitee.com/weicaixun/hxgSpecRepo.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'ImagesPicker_Example' do
  pod 'ImagesPicker', :path => '../'
  pod 'SnapKit', '~> 4.0.0'
  pod 'BaseLib', '~> 0.1.0'
  pod 'RxDataSources', '~> 3.0.2'

end

